// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmydhmguxppsfjtjsutp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhteWRobWd1eHBwc2ZqdGpzdXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzYzNjMsImV4cCI6MjA2NDk1MjM2M30.5qe9DzaakUpIF-XjNVf_P-yQeZjuM9T7DdPHaycf-mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);